### ISSUE TITLE
Building automatically

### ISSUE THREAD

**Issue by dirkk0** [donmccurdy/aframe-inspector-plugin-recast#7]
Hi,

  I temporarily put your two FPS style examples here:
https://curious-electric.com/w/experiments/aframe/navmesh/1.html
https://curious-electric.com/w/experiments/aframe/navmesh/2.html
As always, one needs to hit ctrl-alt-i to enter the inspector and build the navmesh first.

A couple of questions/remarks:
a) in example 1 the red cube in the middle doesn't seem to influence the navmesh; why is that?
b) I changed the starting point of the rig in example 2 to x:-11 - hence you start in the hallway and can move in the navmesh all the way up in the dungeon. :-)

and most importantly
c) is there a way to trigger the inspector-plugin (i.e. the mesh build) via JavaScript?

Thanks,
  Dirk

**Comment by donmccurdy** [comment]
a) I think it's an effect of the agentMaxClimb setting, if you use something lower like 0.2 it will start affecting the navmesh. Otherwise it's too low to block the player and too small to be treated as a raised area, probably.
b) nice! that's a good change i think

c) Not currently, what do you have in mind? I don't really want people triggering it "realtime" in an app, even though that would technically be a hacky way to support moving obstacles, because it does involve a real instance that I need to keep running. If you want to re-host the [backend service](https://github.com/donmccurdy/aframe-inspector-plugin-recast/blob/master/function.js) and set a custom `serviceURL`, you are of course free to call that from JS. :) Deploying just involves running `now --docker`.
